/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupUsernameRouteImport } from './routes/setup-username'
import { Route as IconRouteImport } from './routes/icon'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextHashRouteImport } from './routes/text.$hash'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as ApiOgHashRouteImport } from './routes/api/og.$hash'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SetupUsernameRoute = SetupUsernameRouteImport.update({
  id: '/setup-username',
  path: '/setup-username',
  getParentRoute: () => rootRouteImport,
} as any)
const IconRoute = IconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextHashRoute = TextHashRouteImport.update({
  id: '/text/$hash',
  path: '/text/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgHashRoute = ApiOgHashRouteImport.update({
  id: '/api/og/$hash',
  path: '/api/og/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/icon': typeof IconRoute
  '/setup-username': typeof SetupUsernameRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/text/$hash': typeof TextHashRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/$hash': typeof ApiOgHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/icon': typeof IconRoute
  '/setup-username': typeof SetupUsernameRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/text/$hash': typeof TextHashRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/$hash': typeof ApiOgHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/icon': typeof IconRoute
  '/setup-username': typeof SetupUsernameRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/text/$hash': typeof TextHashRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/$hash': typeof ApiOgHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/icon'
    | '/setup-username'
    | '/profile/$username'
    | '/text/$hash'
    | '/api/auth/$'
    | '/api/og/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/icon'
    | '/setup-username'
    | '/profile/$username'
    | '/text/$hash'
    | '/api/auth/$'
    | '/api/og/$hash'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/icon'
    | '/setup-username'
    | '/profile/$username'
    | '/text/$hash'
    | '/api/auth/$'
    | '/api/og/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  IconRoute: typeof IconRoute
  SetupUsernameRoute: typeof SetupUsernameRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  TextHashRoute: typeof TextHashRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOgHashRoute: typeof ApiOgHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-username': {
      id: '/setup-username'
      path: '/setup-username'
      fullPath: '/setup-username'
      preLoaderRoute: typeof SetupUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon': {
      id: '/icon'
      path: '/icon'
      fullPath: '/icon'
      preLoaderRoute: typeof IconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text/$hash': {
      id: '/text/$hash'
      path: '/text/$hash'
      fullPath: '/text/$hash'
      preLoaderRoute: typeof TextHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$hash': {
      id: '/api/og/$hash'
      path: '/api/og/$hash'
      fullPath: '/api/og/$hash'
      preLoaderRoute: typeof ApiOgHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  IconRoute: IconRoute,
  SetupUsernameRoute: SetupUsernameRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  TextHashRoute: TextHashRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOgHashRoute: ApiOgHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
